### ISSUE TITLE
Develop initial AIP generation component

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/pds-deep-archive#3]
> L5.NSS.2 – The tool shall be capable of generating a valid Archive Information Package transfer manifest (Product_AIP) and PDS4 XML label in accordance with the PDS4 Information Model. 

This task includes:
- [x] creation of the new AIP product 
- [x] update the SIP to include the checksum of the newly created AIP (this value is currently all zeros)

## Overview
Here is a template AIP to work from: [template_Product_AIP_v1D00.xml.txt](https://github.com/NASA-PDS-Incubator/pds-deep-archive/files/4245413/template_Product_AIP_v1D00.xml.txt)

You will also need to create 2 other files (checksum manifest could be an input file, which we have TBD PR out there to update):
* checksum manifest - this file is a 2-column, tab-delimited MD5 checksum file (see 
[ladee_mission_bundle_bundle_checksums_v1.0.tab.txt](https://github.com/NASA-PDS-Incubator/pds-deep-archive/files/4245447/ladee_mission_bundle_bundle_checksums_v1.0.tab.txt)
  * each row should be `<checksum><tab><relative-filepath><crlf>`
* transfer manifest - this is a 2-column, fixed-width table (see [ladee_mission_bundle_TransferManifest_inventory_v1.0.tab.txt](https://github.com/NASA-PDS-Incubator/pds-deep-archive/files/4245479/ladee_mission_bundle_TransferManifest_inventory_v1.0.tab.txt) although we are not following these paths necessarily)
  * each row should have 2 columns, each column should be 255 characters long. use whitespace as filler.
  * `<product_lidvid>    (dozens more spaces)    <relative-filepath><crlf>`

## File Naming
Similar to the SIP file naming, let's use the bundle name with some add-ons (correct me if this is not what we did for SIP):
* <bundle_lid>_aip_v1.0.xml
* <bundle_lid>_checksum_manifest_v1.0.tab
* <bundle_lid>_transfer_manifest_v1.0.tab

## Things to be aware of
* From the looks of it, we probably should have just created the AIP first and then tackled the SIP.
* It appears we basically just need to output some other intermediate files that are just different permutations of the information needed for the SIP manifest.
* Per note above, the checksum manifest will eventually be an optional input to the software, so keep that in mind during implementation.

**Comment by nutjob4life** [comment]
@jordanpadams question: in the XML label sample (attached to the issue) there are entries for `$CHECKSUM_RECORDS` and `$TRANSFER_RECORDS`. Does this mean putting the entire contents of the generated checksum manifest and transfer manifest into the XML label?

**Comment by nutjob4life** [comment]
@jordanpadams one other quickie: in the sample XML label (attached to the issue), the `File_Area_Transfer_Manifest` has a `File` child with an `md5_checksum` element, but the similar `File_Area_Checksum_Manifest` has a `File` child without the `md5_checksum`. Just want to confirm that _that_ is intentional.

**Comment by jordanpadams** [comment]
> @jordanpadams question: in the XML label sample (attached to the issue) there are entries for `$CHECKSUM_RECORDS` and `$TRANSFER_RECORDS`. Does this mean putting the entire contents of the generated checksum manifest and transfer manifest into the XML label?

@nutjob4life  oops. Def not clear. Those should be the number of records in each table. Should probably be *_NUM_RECORDS.

**Comment by jordanpadams** [comment]
> @jordanpadams one other quickie: in the sample XML label (attached to the issue), the `File_Area_Transfer_Manifest` has a `File` child with an `md5_checksum` element, but the similar `File_Area_Checksum_Manifest` has a `File` child without the `md5_checksum`. Just want to confirm that _that_ is intentional.

Ignore md5_checksum. I removed it bc it doesn't seem to make sense to duplicate this value in 20 places.
