### ISSUE TITLE
SIP Generator not outputting correctly for spice example bundle

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/pds-deep-archive#39]
**Describe the bug**
When I run the latest `pds-deep-archive` software, there are a few issues with the output:

```
bin/pds-deep-archive -b https://naif.jpl.nasa.gov/pub/naif/pds/pds4/insight/ -s PDS_NAI insight_spice/bundle_insight_spice_v001.xml -d
```
Note: I pointed the software at v1 of the bundle (`bundle_insight_spice_v001.xml `) so it should take that version and the versions it is referencing into account.

1. The SIP only contains 1 product (should contain many more)
2. ~~The checksum manifest and transfer manifest both include all versions of the collections, but these should only contain the versions referenced from `bundle_insight_spice_v001.xml`.~~ See #41

**Comment by jordanpadams** [comment]
@nutjob4life btw, I downloaded this data and put it out on our test server `/data/home/pds4/testdata/insight_spice`

**Comment by nutjob4life** [comment]
I'd like to split this into two issues, one effecting the AIP generation and one this SIP generation, in order to make more controlled commits & pulls to address these issues.
